### ISSUE TITLE
Volume Keys Without Power Buttons

### ISSUE THREAD

**Issue by daconrad0** [marrobHD/firetv-card#8]
**Is your feature request related to a problem? Please describe.**
Is it possible to have the volume buttons controlled by your card without having the TV power buttons.  I use scripts to turn on the TV and set the source.   I have attached a sample from my configuration

![D650FB2C-1067-4DBB-9C9E-7182553A6F80](https://user-images.githubusercontent.com/48894833/99878135-43c3d980-2bd1-11eb-84ee-c6f02a8826d4.png)

**Describe the solution you'd like**
Have options for TV Power and TV Volume instead of the current TV

**Describe alternatives you've considered**
Currently have have a your card in a vertical stack card.  I have the volume controls as a grid card in the bottom layer.

**Additional context**

**Comment by marrobHD** [comment]
Yeah its possible, just add the specfic buttons to your lovelace card configuration.
Example:

```yaml
        volume_up:
          service media_player.volume_up
          service_data:
            entity_id: media_player.chromecast
        volume_down:
          service media_player.volume_down
          service_data:
            entity_id: media_player.chromecast
        volume_mute:
          service media_player.volume_mute
          service_data:
            entity_id: media_player.chromecast
```

Thank you!
