### ISSUE TITLE
2 power buttons?

### ISSUE THREAD

**Issue by broyuken** [marrobHD/firetv-card#9]
Why are there 2 power buttons? Can I control 2 devices with this card? IE Sound bar and TV?

Also, could you allow separate services for turn_on and turn_off like how universal media players do it?

```
commands:
  turn_on:
    service: switch.turn_on
    data:
      entity_id: switch.living_room_tv_power
  turn_off:
    service: switch.turn_off
    data:
      entity_id: switch.living_room_tv_power
```
